name: PDF Exporting

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:

  convert:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:

    # - name: Install pandoc
    #   run: sudo apt-get install -y pandoc

    # - name: Install xelatex
    #   run: sudo apt-get install -y texlive-xetex

    # - name: Install lmodern
    #   run: sudo apt-get install lmodern

    # - name: Install fonts
    #   run: sudo apt-get install texlive-fonts-recommended

    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name 'Tom Vautray'
        git config --global user.email 'tom-vautray@hotmail.fr'
    
    - name: Git pull
      run: git pull
    
    - name: Git checkout
      run: git checkout pdf-cv-releasing

    - name: Screenshot
      run: chromium --headless --screenshot="cv.png" https://m4jor-tom.github.io/
    
    - name: Getting permission to convert
      run: sudo echo <policy domain="coder" rights="read | write" pattern="PDF" />' > /etc/ImageMagick-6/policy.xml
    
    - name: Convert png to pdf
      run: convert cv.png cv.pdf

    - name: Commit & Push
      run: |
        git add --all
        git commit -m "Cv commit by convert job"
        git push
