name: PDF Exporting

on:
  push: 
    branches: ['master']

jobs:

  convert:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:

    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name 'Tom Vautray'
        git config --global user.email 'tom-vautray@hotmail.fr'
    
    - name: Git pull
      run: git pull
    
    - name: Git checkout
      run: git checkout pdf-cv-releasing
    
    - name: Reset pdf-cv-releasing branch to master
      run: git reset --hard master
      
    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: index.html
        outputFile: generated/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

    - name: Commit & Push
      run: |
        git add --all
        git commit -m "Cv commit by convert job"
        git push --force
