name: PDF Exporting

on:
  push:
    branches: [ "master" ]

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
    - name: Install xelatex
      run: sudo apt-get install -y texlive-xetex
    - uses: actions/checkout@v3
    - name: Build pdf for curiculum vitae
      run: |
        pandoc https://m4jor-tom.github.io/ -f html-native_divs -o cv.pdf --pdf-engine=xelatex
    - name: Archive production artifacts for pdf
      uses: actions/upload-artifact@v3
      with:
        name: cv
        path: |
          cv.pdf