name: PDF Exporting

on:
  push:
    branches: [ "master" ]

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
    - name: Install xelatex
      run: sudo apt-get install -y texlive-xetex
    - uses: actions/checkout@v3
    - name: Build pdf for curiculum vitae
      run: |
        pandoc https://m4jor-tom.github.io/ -f html-native_divs -o cv.pdf --pdf-engine=xelatex

  upload:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'cv.pdf'
        destination: 'github-actions/cv.pdf'
