name: PDF Exporting

on:
  push:
    branches: [ "master" ]

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
    - name: Install xelatex
      run: sudo apt-get install -y texlive-xetex
    - uses: actions/checkout@v3
    - name: Build pdf for curiculum vitae
      run: |
        pandoc https://m4jor-tom.github.io/ -f html-native_divs -o cv.pdf --pdf-engine=xelatex
    - name: Archive production artifacts for pdf
      uses: actions/upload-artifact@v3
      with:
        name: cv
        path: |
          cv.pdf
          
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name 'Tom Vautray'
        git config --global user.email 'tom-vautray@hotmail.fr'

    - name: Commit & Push
      run: |
        git add cv.pdf
        git commit -m "Ajout ou modification de fichier"
        git push
