name: PDF Exporting

on:
  push:
    branches: [ "master" ]

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
    - name: Install xelatex
      run: sudo apt-get install -y texlive-xetex
    - uses: actions/checkout@v3
    - name: Build pdf for curiculum vitae
      run: |
        pandoc https://m4jor-tom.github.io/ -f html-native_divs -o cv.pdf --pdf-engine=xelatex
    - name: Archive production artifacts for pdf
      uses: actions/upload-artifact@v3
      with:
        name: cv
        path: |
          cv.pdf
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./cv.pdf
        asset_name: cv.pdf
        asset_content_type: application/pdf